Algoritmo "Entrada e saída de dados"

// Descrição   : Entrada e saída de dados
// Autor(a)    : Ana Lúcia Coutinho
// Data atual  : 08/06/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite o seu nome")
   leia(nome)
   escreval ("Digite a sua nota")
   leia(nota)
   
   escreval("o nome digitado foi:" , nome)
   escreval("a nota digitada foi:" , nota)

Fimalgoritmo